baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Leo's Professional Website
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Achtergronden
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    # - name: Blog
    #   url: blog
    #   weight: 2
params:
  # blogPageURL: blog
  contactButtonLabel: Neem contact op
  contactLink: '#contact'
  copyright: All right reserved copyright © Leo Timmermans 2022
  footerLogo: images/site-navigation/website_logo_leo_1.png
  formspreeURL: https://formspree.io/f/xjvzkqkd
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/website_logo_leo_1.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/ljjtimmermans/
      weight: 1
    # - icon: fa-youtube-square
    #   url: https://www.youtube.com/
    #   weight: 2
    # - icon: fa-twitter-square
    #   url: https://twitter.com/
    #   weight: 3
